spring:
  application:
    name: rubyy-ai-code
  profiles:
    active: local
  # redis
  data:
    redis:
      host: localhost
      port: 6379
#      password: 12345
      ttl: 3600
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000


  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rubyy_ai_code
    username: root
    password: 123456

server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.rq.rubyyaicode.controller
